[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
azure_core = "0.19.0"
azure_messaging_servicebus = "0.19.0"
wasmtime = "19.0.1"
wasmtime-wasi = "19.0.1"
wit-component = "0.202.0"
