[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.79"
azure_messaging_servicebus = "0.19.0"
runtime = { version = "0.1.0", path = "../runtime" }
wasmtime = "19.0.1"
wasmtime-wasi = "19.0.1"
