[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1.79"
bindings = { version = "0.1.0", path = "../../crates/bindings" }
runtime = { version = "0.1.0", path = "../../crates/runtime" }
tokio = { version = "1.36.0", features = ["full"] }
